### ISSUE TITLE
Want to get clarity on how to give the input for zero-shot NER.

### ISSUE THREAD

**Issue by bhavuk-singhal** [BeyonderXX/InstructUIE#12]
I have few questions:-

1. Here are the list of prompts given in the paper for NER:-
         a. Please list all entity words in the text that fit the category. Output format is "type1: word1; type2: word2".
         b. Please find all the entity words associated with the category in the given text. Output format is "type1: word1; type2: word2".
         c. Please tell me all the entity words in the text that belong to a given category. Output format is "type1: word1; type2: word2".
         d. Please list all entity words in the text that fit the category. Output format is word1, word2.
         e. Given options, please tell me the categories of all the listed entity words. Output format is "type1: word1; type2: word2".
So, are these prompts dataset specific? And if not, so does that mean that all of these prompts will give best results on all of the datasets? And if it is dataset specific, then can you please throw a light on this like which prompt to be used given the dataset specifics.

2. What is the exact format of input to the model for zero-shot NER. Let's say if I want to use prompt p1 = "Please list all entity words in the text that fit the category. Output format is "type1: word1; type2: word2"." and the sentence s = "My name is alexa and I live in washigton" and options  O = "location, person, organization, miscellaneous". So input would be """p1 + \n + 'Option: ' + O + \n + 'Text: '+s""". Right?

**Comment by BeyonderXX** [comment]
Hi,

**Comment by BeyonderXX** [comment]
Hi,
1. These prompts are not dataset specific, their performance gap is insignificant. We will add some ablation study experiments to show the model performance under different prompts settings.
2. Almost right! Plz add "\nAnswer:" at the end of your input.

Xiao Wang
