### ISSUE TITLE
Zero-shot NER experiment settings

### ISSUE THREAD

**Issue by Spico197** [BeyonderXX/InstructUIE#13]
Hi, there. Thanks for the excellent work!
Since the NER datasets in zero-shot settings are also included in the IE INSTRUCTIONS dataset, I'm wondering if there are special instructions for zero-shot experiments?
Do we have to remove all the seven NER datasets and train a new model to get fair results?

Thanks very much!

**Comment by BeyonderXX** [comment]
Hi! 
For the zero-shot experiments, we removed all test-related datasets from the training set, while the instruction was the same as the supervised.

Xiao Wang

**Comment by Spico197** [comment]
Got it. Thank you very much for your quick response~
