### ISSUE TITLE
如何改成支持中文的

### ISSUE THREAD

**Issue by xiaoxiaobai321** [BeyonderXX/InstructUIE#15]
如何改成支持中文的

**Comment by xxllp** [comment]
+1

**Comment by cristianohello** [comment]
+1

**Comment by KelleyYin** [comment]
Has anyone tried to use mT5 in Chinese data?

**Comment by BeyonderXX** [comment]
我觉得需要以下改动：
1.基座模型支持中文，比如mT5, Chinese LLaMA;
2.将instruction修改为中文版本；
3.对于代码中输出部分，关于英文输出的后处理部分修改为中文逻辑。

大概就可以了。

**Comment by vv521** [comment]
> 我觉得需要以下改动： 1.基座模型支持中文，比如mT5, Chinese LLaMA; 2.将instruction修改为中文版本； 3.对于代码中输出部分，关于英文输出的后处理部分修改为中文逻辑。
> 
> 大概就可以了。

大佬有没有公众号或者csdn帖子可以出一下实战贴吗？
