### ISSUE TITLE
deepspeed模式下如何debug

### ISSUE THREAD

**Issue by xiaoxiaobai321** [BeyonderXX/InstructUIE#17]
使用deepspeed就不能使用pdb，这是为什么
在使用deepspeed的情况下如何调试
在不使用deepspeed的情况下要改哪些地方，才能关掉deepspeed这个功能

**Comment by BeyonderXX** [comment]
直接从对应python文件启动训练/验证，输入的参数相同，但是把 --deepspeed 参数移除，就可以像普通python一样调试了。另外建议用小模型调试，不然你的GPU可能顶不住 :)
