### ISSUE TITLE
run eval_flan-t5.sh  with do_demo 

### ISSUE THREAD

**Issue by dignjun** [BeyonderXX/InstructUIE#18]
Please enter your input to the model, or enter 'quit' to exit: Please enter your input to the model, or enter 'quit' to exit: 06/09/2023 18:02:35 - INFO - __main__ - Serving the model as a demo...
Please enter your input to the model, or enter 'quit' to exit: Please enter your input to the model, or enter 'quit' to exit:
Traceback (most recent call last):
  File "src/run_uie.py", line 560, in <module>
    main()
  File "src/run_uie.py", line 553, in main
    _, preds, _ = trainer.prediction_step(model, inputs=inputs, prediction_loss_only=False)
  File "/home/nlp/ding/InstructUIE/src/uie_trainer.py", line 263, in prediction_step
    gen_kwargs = self._gen_kwargs
AttributeError: 'UIETrainer' object has no attribute '_gen_kwargs'

**Comment by Cbiswadeep** [comment]
Hi I think I fixed this issue: 
1.    Pass **gen_kwargs in the function definition
  def prediction_step(
        self,
        model: nn.Module,
        inputs: Dict[str, Union[torch.Tensor, Any]],
        prediction_loss_only: bool,
        ignore_keys: Optional[List[str]] = None,
        **gen_kwargs,
    ) -> Tuple[Optional[float], Optional[torch.Tensor], Optional[torch.Tensor]]:
        """
2. Add this line: gen_kwargs = gen_kwargs.copy() before gen_kwargs is used like this:

        # XXX: adapt synced_gpus for fairscale as well
        gen_kwargs = gen_kwargs.copy()
        gen_kwargs["synced_gpus"] = True if is_deepspeed_zero3_enabled() else False

**Comment by BeyonderXX** [comment]
@Cbiswadeep Thanks for your contribution!
