### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by gzw209** [BeyonderXX/InstructUIE#2]
Hello, can you please publish this IE INSTRUCTIONS.?

**Comment by BeyonderXX** [comment]
Thank you for your attention. We have yet to determine the version of the data set, including the expansion of the number of data sets and the format adjustment. The version of Instruct-UIE will continue to be upgraded, and in the next version, we will open-source the final dataset.

**Comment by BeyonderXX** [comment]
Hello, we have released our dataset.
You can download the data from [Baidu NetDisk](https://pan.baidu.com/s/1R0KqeyjPHrsGcPqsbsh1XA?from=init&pwd=ybkt) or [Google Drive](https://drive.google.com/file/d/1T-5IbocGka35I7X3CE6yKe5N_Xg2lVKT/view?usp=share_link).

Xiao Wang
