### ISSUE TITLE
Instructions in the released dataset

### ISSUE THREAD

**Issue by Sreyan88** [BeyonderXX/InstructUIE#20]
Hi there!
Great paper and thanks for releasing the dataset. However, may I please ask where I can find the expert written instructions for the dataset? In the drive link I just found the json-ified IE datasets. Thank You in advance!

**Comment by BeyonderXX** [comment]
Hi, thank you for your attention. 
The instructions we wrote for the tasks are stored here: [link](https://github.com/BeyonderXX/InstructUIE/blob/master/configs/instruction_config.json). 
Considering that the instruction and sample are directly combined, a lot of redundancy will be caused when storing. So we adopted a runtime-generated strategy. If you only wish to generate training/validation data. You only need to remove --do_train and  --do_predict, and the log will tell you where the generated data is saved.
