### ISSUE TITLE
Question that whether this method support Chinese Task?

### ISSUE THREAD

**Issue by 976230600** [BeyonderXX/InstructUIE#21]
Hi 大佬，想问下这个工作是否支持中文呢？因为我看训练数据集好像都是英文的？第一次看这个领域的工作，比较小白哈哈哈。谢谢大佬！

**Comment by BeyonderXX** [comment]
你好！ 
我们这个工作是在英文上面做的，如果要做中文任务，对代码做轻微修改就可以。
关于如何修改，我在这个提问中提了几个关键点。
#15

**Comment by 976230600** [comment]
感谢回复！请问在完成模型替换和代码修改以后，在自己的数据集比较小的情况下，还有必要再训练进行微调吗？主要是考虑可能还是需要按照您工作中的流程练一下模型，效果应该会更好吧

**Comment by BeyonderXX** [comment]
InstructUIE 的工作是在英文上做的，直接上中文效果应该不好，所以微调是必须的。
如果你数据比较少，建议找些开源的中文语料混在一起做 joint learning，增强模型的中文泛化能力，应该会对你的任务有帮助。

**Comment by 976230600** [comment]
了解，感谢！有问题再向您请教！

**Comment by 976230600** [comment]
您好！我又来了）
我在考虑这篇工作是否有可能扩展一下文档级信息抽取的任务，但因为还缺少调研所以先设想一下，或许会比较缺少数据集（尤其是中文数据集），以及LLM不到一定参数规模的话，对长文本文档的理解会比较差。方便的话可以听一听您的看法嘛？

**Comment by BeyonderXX** [comment]
文档级NER很难做，你可以试一下chatgpt的效果，那个基本就是目前能做到的天花板。另外模型大确实长文档理解会好一点，但是不是质的变化，这是我个人的LLM使用经验。建议想想其他方案，比如加一些先验规则。

**Comment by 976230600** [comment]
star好说hhh
我有在chatgpt上试过一些文档，在比较简单的提示下，新闻之类完全的非结构化文档基本没法看，文书之类格式措辞比较规范严谨的文档，效果就还挺不错的。所以我想那这个任务可能做不了那么通用，而且有点杀鸡用牛刀的味……我也再考虑一下，感谢建议！
