### ISSUE TITLE
开源的checkpoint的评估结果与论文差异较大？

### ISSUE THREAD

**Issue by xueyongfu11** [BeyonderXX/InstructUIE#24]
自己根据开源的checkpoint评估的结果：
                                      ACE 2004	0.799446
                           ACE 2005_sample_15000	0.823431
                                          AnatEM	0.906356
                                           bc2gm	0.853468
                                        bc4chemd	0.903051
                                          bc5cdr	0.896358
                              Broad Tweet Corpus	0.807502
                         CoNLL 2003_sample_15000	0.920924
                                          FabNER	0.778983
                                     FindVehicle	0.862235
                                       GENIA_NER	0.760505
                                       HarveyNER	0.881229
                                       mit-movie	0.891786
                                  mit-restaurant	0.825387
                                       MultiNERD	0.905533
                                            ncbi	0.894619
                          Ontonotes_sample_30000	0.907458
                                     PolyglotNER	0.581986
                          TweetNER7_sample_15000	0.654393
                                      WikiANN en	0.609424
                                      WikiNeural	0.877284
                                         Average	0.825779

论文当中的Average是0.85，差了3个点。

**Comment by BeyonderXX** [comment]
造成开源模型和论文report的结果差异的原因就在于数据采样，不同的采样对应的效果有一定的方差。
最初始的结果是在Bytedance的机器上跑出来的，因为Bytedance的数据安全问题，模型无法审核到外网。开源版本的模型，是几周后，在 Fudan NLP 新到的 A800 机器上训练出来的，有一定方差。而 InstructUIE 的训练成本过于高昂，希望可以理解。

Xiao Wang

**Comment by xueyongfu11** [comment]
嗯，感谢回复

**Comment by charosen** [comment]
@xueyongfu11 @BeyonderXX 您好，两位大佬，我想请教一下，11b模型跑一次评估结果，大概需要多长时间
