### ISSUE TITLE
When will the dataset and the checkpoint files been released？

### ISSUE THREAD

**Issue by Hjunchi** [BeyonderXX/InstructUIE#3]

**Comment by BeyonderXX** [comment]
Hello, we have released our dataset.
You can download the data from [Baidu NetDisk](https://pan.baidu.com/s/1R0KqeyjPHrsGcPqsbsh1XA?from=init&pwd=ybkt) or [Google Drive](https://drive.google.com/file/d/1T-5IbocGka35I7X3CE6yKe5N_Xg2lVKT/view?usp=share_link).

Xiao Wang

**Comment by ShallTearchen** [comment]
> Hello, we have released our dataset. You can download the data from [Baidu NetDisk](https://pan.baidu.com/s/1R0KqeyjPHrsGcPqsbsh1XA?from=init&pwd=ybkt) or [Google Drive](https://drive.google.com/file/d/1T-5IbocGka35I7X3CE6yKe5N_Xg2lVKT/view?usp=share_link).
> 
> Xiao Wang

Looking forward to releasing the checkpoint !

**Comment by BeyonderXX** [comment]
Hi,
We have released our 11B UIE model, click [here](https://huggingface.co/ZWK/InstructUIE) for download.
