### ISSUE TITLE
更小的模型效果如何

### ISSUE THREAD

**Issue by powerful6** [BeyonderXX/InstructUIE#34]
非常欣赏这篇论文和开源代码。
有个问题想请教一下：作者试过参数量小一点的模型吗？比如Flan-T5-3B，GPT2等，效果会差很多吗？

**Comment by BeyonderXX** [comment]
感谢关注！
我们确实做了这样的实验，论文仍然在审稿中，所以没有更新。
可以放个图说明：
<img width="343" alt="image" src="https://github.com/BeyonderXX/InstructUIE/assets/42961051/3a2e8c15-9f90-4102-8b0e-1afcac9d15bf">

Xiao Wang

**Comment by powerful6** [comment]
感谢作者的解答！论文和代码让我受益匪浅
祝 早日中稿
