### ISSUE TITLE
BERT-BASE

### ISSUE THREAD

**Issue by pangpang-xuan** [BeyonderXX/InstructUIE#44]
您好 我想问一下这栏的bert-base的分数的来源是什么？怎么复现您的这个分数呢？感谢您

**Comment by BeyonderXX** [comment]
是我们自己实现的，可以参考这个库，处理下数据格式就可以跑。

https://github.com/liuyukid/transformers-ner

**Comment by pangpang-xuan** [comment]
感谢您的回答 最后几个问题 
1.您当时是用bert+crf还是softmax呢？
2.我发现ace2005数据集存在嵌套ner的现象 请问您是怎么处理这个现象的呢？
十分感谢您

**Comment by ShDdu** [comment]
您好，我看了您提供的这个BERT库，但是发现里面的方法似乎不能识别嵌套实体，但是在InstructUIE里面涉及很多嵌套实体的数据集，请问您在复现bert-base实验时对嵌套实体是怎么处理的呢？
