### ISSUE TITLE
How much GPU memory do I need for fine-tuning and inference?

### ISSUE THREAD

**Issue by DYF-AI** [BeyonderXX/InstructUIE#5]
How much GPU memory do I need for fine-tuning and inference?

**Comment by BeyonderXX** [comment]
With A100 * 8, which are completely connected by Nvlinks, it might cost 46 hours to tune flan-t5 11B model.

**Comment by vv521** [comment]
> With A100 * 8, which are completely connected by Nvlinks, it might cost 46 hours to tune flan-t5 11B model.
作者您好，请问单独对ner   RE 部分进行微调，需要gpu最低配置是多少啊？

**Comment by BeyonderXX** [comment]
这个要看你的需求，包括你要训练多大的模型，有什么GPU资源。

如果是单卡训练，一个经验性计算方式  18*model_size (B) ，如果你的gpu memory 可以cover，就能训练。
如果是多卡训练，那就要用deepspeed 的zero，或者更复杂的 Pipeline，这个取决于你的GPU数量，连通硬件，不好给出结论。
