### ISSUE TITLE
what is the means for samlpe_15000 in dataset?

### ISSUE THREAD

**Issue by zplovekq** [BeyonderXX/InstructUIE#6]
the paper shows sample 10000 for dataset.
what the means for the CoNLL 2003_sample_15000 and Ontonotes_sample_30000 in the dataset folder?

**Comment by BeyonderXX** [comment]
你好，感谢关注！我们中途尝试了各种采样方法，做了几个常用数据集的过采样，对比发现效果几乎没有变化。这块逻辑遗留在代码里，没有改，会尽快修复。
