### ISSUE TITLE
The mismatch between InstructUIE datasets and UIE datasets

### ISSUE THREAD

**Issue by gao-xiao-bai** [BeyonderXX/InstructUIE#7]
EE datasets in InstructUIE such as ACE05 and CASIE have fewer examples than these datasets in UIE.  Moreover, there is no offset annotation in these datasets in InstructUIE. What causes these differences?
Datasets statistics in your paper
![image](https://user-images.githubusercontent.com/34589522/237025985-a740bc8d-0ae5-49ee-9e9b-a66dacf614c6.png)
Datasets statistics in the UIE paper
![image](https://user-images.githubusercontent.com/34589522/237026363-d4f96236-c8be-4b47-854e-d8a8b970eb97.png)

**Comment by gao-xiao-bai** [comment]
Thank you for your clarification. However, for the data, why is "pos" here empty?
 {
        "sentence": "Malaysia ' s prison department has agreed to allow jailed politician Anwar Ibrahim to attend his daughter ' s wedding ceremony Friday after his bail hearing , his lawyer said Thursday .",
        "events": [
            {
                "trigger": "wedding",
                "type": "marry",
                "pos": [],
                "arguments": [
                    {
                        "name": "daughter",
                        "role": "person",
                        "pos": []
                    }
                ]
            }
        ]
    },

**Comment by zccccb** [comment]
Thanks for your question. We did not use this information during the experiment. Due to the large number of datasets, unnecessary information was not saved in order to compress the storage space.
