### ISSUE TITLE
When can we expect the releasing of the checkpoint?

### ISSUE THREAD

**Issue by bhavuk-singhal** [BeyonderXX/InstructUIE#8]

**Comment by BeyonderXX** [comment]
Because our model is in cooperation with Bytedance, due to security issues, it has not yet been reviewed. Opening ckpt will take some time. This work is still being optimized, please continue to pay attention.

**Comment by BeyonderXX** [comment]
Hi, We have released our 11B UIE model, click [here](https://huggingface.co/ZWK/InstructUIE) for download.
