### ISSUE TITLE
4块titan微调模型时显存不够了，用glm-6b换了flan-t5的模型（fp16），改小了batch参数，还是不行，请问有哪些参数还可以调一下，并且不怎么影响效果的

### ISSUE THREAD

**Issue by yulz1997** [BeyonderXX/InstructUIE#9]

**Comment by BeyonderXX** [comment]
你好！6B模型，如果全量微调，理论上需要，6*16=96G显存，如果开zero3，每张卡24G显存，已经超了。

**Comment by yulz1997** [comment]
您好，我想问下如果用instruction tuning glm的代码（LoRA），加上您的微调数据，是不是就和您的方法差不多呢（少了几个辅助任务），想快点出个结果，这样是不是比较好的方案。

**Comment by BeyonderXX** [comment]
没有试过LoRA，不太确定效果如何。不加辅助任务，会低1-2个点。
